### ISSUE TITLE
App install issue in R2012B on OS X 10.8.5

### ISSUE THREAD

**Issue by gallagth** [jdelacroix/simiam#11]
I get the following exception when trying to install the simiam.mlappinstall app in Matlab:

```
com.mathworks.jmi.MatlabException: Reference to a cleared variable mlappfile.
at com.mathworks.jmi.NativeMatlab.SendMatlabMessage(Native Method)
at com.mathworks.jmi.NativeMatlab.sendMatlabMessage(NativeMatlab.java:219)
at com.mathworks.jmi.MatlabLooper.sendMatlabMessage(MatlabLooper.java:120)
at com.mathworks.jmi.Matlab.mtFeval(Matlab.java:1540)
at com.mathworks.jmi.MatlabWorker.feval(MatlabWorker.java:197)
at com.mathworks.appmanagement.InstallAppMatlabWorker.doOnMatlabThread(InstallAppMatlabWorker.java:20)
at com.mathworks.appmanagement.InstallAppMatlabWorker.doOnMatlabThread(InstallAppMatlabWorker.java:7)
at com.mathworks.appmanagement.AbstractAppManagementMatlabWorker.runOnMatlabThread(AbstractAppManagementMatlabWorker.java:21)
at com.mathworks.jmi.MatlabWorker$2.run(MatlabWorker.java:79)
at com.mathworks.jmi.MatlabWorker.start(MatlabWorker.java:248)
at com.mathworks.appmanagement.AbstractAppManagementMatlabWorker.go(AbstractAppManagementMatlabWorker.java:52)
at com.mathworks.appmanagement.PackagingApiImpl.extract(PackagingApiImpl.java:25)
at com.mathworks.appmanagement.AppManagementApiImpl.install(AppManagementApiImpl.java:153)
at com.mathworks.appmanagement.AppManagementApiImpl.install(AppManagementApiImpl.java:75)
```

I'm not familiar with Matlab apps so can I use the software without installing that file?

**Comment by jdelacroix** [comment]
Yes, you can just type 'launch' from the unzipped folder (the one that contains that file and everything else).
